homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 57.43
  longitude: 11.59
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  customize:
    sun.sun:
      hidden: true
    script.radio_paradise:
      hidden: true
    script.sr_p1:
      hidden: true
    script.sr_p3:
      hidden: true
    script.sr_p4:
      hidden: true
    script.sr_radioapan:
      hidden: true

    group.Switch:
      hidden: true

http: !include http.yaml

switch:
  platform: tellstick
  datatype_mask: 127

light:
  platform: tellstick
  datatype_mask: 127

device_tracker: !include devicetracker.yaml

media_player:
  - platform: kodi
    url: http://192.168.1.15:8080/jsonrpc

#  - platform: samsungtv
#    host: 192.168.1.33

sensor:
  platform: tellstick
  only_named: 1
  11: Frys
  31: Ute
  80: Våning 3
  53: Vind
  datatype_mask: 1

verisure: !include verisure.yaml

discovery:

frontend:

conversation:

history:

logbook:

sun:

group:
  Belysning:
    view: yes
    entities:
      - group.Ute
      - group.Fnster
  Multimedia:
    view: yes
    entities:
      - group.Musik
  Klimat:
    view: yes
    entities:
      - group.Temperatur
      - group.Fuktighet
  Ute:
    - switch.Baksida
    - switch.Entre
    - switch.Balkong
  Fönster:
    - switch.van3_fonster1
    - switch.van3_fonster2
  Musik:
    - media_player.tak
    - input_select.kanal
  Temperatur:
    - sensor.frys_temperature
    - sensor.hall_nere_temperature
    - sensor.hall_uppe_temperature
    - sensor.vardagsrum_temperature
    - sensor.ute_temperature
    - sensor.vning_3_temperature
    - sensor.vind_temperature
  Fuktighet:
    - sensor.hall_nere_humidity
    - sensor.hall_uppe_humidity
    - sensor.ute_humidity
    - sensor.ute_temperature_2

automation:
  - alias: Turn on lights outside at sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.Ute

  - alias: Turn off lights outside at sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      service: homeassistant.turn_off
      entity_id: group.Ute

  - alias: Turn off radio
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
        state: 'armed_away'
      - platform: state
        entity_id: input_select.kanal
        state: Av
    action:
      service: media_player.media_pause
      entity_id: media_player.tak

  - alias: Turn off third floor window light in the evening
    trigger:
      platform: time
      after: '22:30:00'
    action:
      service: homeassistant.turn_off
      entity_id: group.fnster

  - alias: Start Radio Paradise
    trigger:
      - platform: state
        entity_id: input_select.kanal
        state: Radio Paradise
    action:
      service: script.radio_paradise
      entity_id: script.ON
  
  - alias: Start P1
    trigger:
      - platform: state
        entity_id: input_select.kanal
        state: P1
    action:
      service: script.sr_p1
      entity_id: script.ON
  
  - alias: Start P3
    trigger:
      - platform: state
        entity_id: input_select.kanal
        state: P3
    action:
      service: script.sp_p3
      entity_id: script.ON
  
  - alias: Start P4
    trigger:
      - platform: state
        entity_id: input_select.kanal
        state: P4
    action:
      service: script.sr_p4
      entity_id: script.ON
  
  - alias: Start Radioapan
    trigger:
      - platform: state
        entity_id: input_select.kanal
        state: Radioapan
    action:
      service: script.sr_radioapan
      entity_id: script.ON
  
input_select:
  kanal:
    name: Kanal
    options:
      - Av
      - Radio Paradise
      - P1
      - P3
      - P4
      - Radioapan
    initial: Av

script:
  radio_paradise:
    alias: Radio Paradise
    sequence:
      - alias: Power on    
        service: media_player.turn_on   
        service_data:
          entity_id: media_player.tak     
      - alias: Set volume  
        service: media_player.volume_set
        service_data:      
          entity_id: media_player.tak     
          volume_level: 0.35               
      - alias: Start radio paradise
        service: media_player.play_media
        service_data:      
          entity_id: media_player.tak     
          media_type: video/mp4           
          media_id: http://stream-dc1.radioparadise.com/rp_192m.ogg
  sr_p1:
    alias: P1
    sequence:
      - alias: Power on    
        service: media_player.turn_on   
        service_data:
          entity_id: media_player.tak     
      - alias: Set volume  
        service: media_player.volume_set
        service_data:      
          entity_id: media_player.tak     
          volume_level: 0.35               
      - alias: Start P1
        service: media_player.play_media
        service_data:      
          entity_id: media_player.tak     
          media_type: video/mp4           
          media_id: http://sverigesradio.se/topsy/direkt/132-hi-mp3
  sr_p3:
    alias: P3
    sequence:
      - alias: Power on    
        service: media_player.turn_on   
        service_data:
          entity_id: media_player.tak     
      - alias: Set volume  
        service: media_player.volume_set
        service_data:      
          entity_id: media_player.tak     
          volume_level: 0.35               
      - alias: Start P3
        service: media_player.play_media
        service_data:      
          entity_id: media_player.tak     
          media_type: video/mp4           
          media_id: http://sverigesradio.se/topsy/direkt/164-hi-mp3
  sr_p4:
    alias: P4
    sequence:
      - alias: Power on    
        service: media_player.turn_on   
        service_data:
          entity_id: media_player.tak     
      - alias: Set volume  
        service: media_player.volume_set
        service_data:      
          entity_id: media_player.tak     
          volume_level: 0.35               
      - alias: Start P4
        service: media_player.play_media
        service_data:      
          entity_id: media_player.tak     
          media_type: video/mp4           
          media_id: http://sverigesradio.se/topsy/direkt/212-hi-mp3
  sr_radioapan:
    alias: Radioapan
    sequence:
      - alias: Power on    
        service: media_player.turn_on   
        service_data:
          entity_id: media_player.tak     
      - alias: Set volume  
        service: media_player.volume_set
        service_data:      
          entity_id: media_player.tak     
          volume_level: 0.35               
      - alias: Start Radioapan
        service: media_player.play_media
        service_data:      
          entity_id: media_player.tak     
          media_type: video/mp4           
          media_id: http://sverigesradio.se/topsy/direkt/2755-hi-mp3
