homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 57.43
  longitude: 11.59
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  
  customize:
    group.all_automations:
      hidden: false
    group.all_scripts:
      hidden: false
    group.all_devices:
      hidden: false
    group.all_switches:
      hidden: false
    group.all_lights:
      hidden: false

group:
  default_view:
    name: Start
    view: yes
    icon: mdi:home
    entities:
      - alarm_control_panel.transistorgatan_alarm
      - device_tracker.androidd539a09108a17440
      - device_tracker.elinsiphone
      - group.radio_1
      - group.radio_2
  lights_view:
    name: Belysning
    view: yes
    icon: mdi:lightbulb
    entities:
      - group.window_lights
      - group.outdoor_lights
  surveillance_view:
    name: Övervakning
    view: yes
    icon: mdi:eye
    entities:
      - alarm_control_panel.transistorgatan_alarm
      - device_tracker.androidd539a09108a17440
      - device_tracker.elinsiphone
      - group.doors
      - camera.mjpeg_camera
  ventilation_view:
    name: Ventilation
    view: yes
    icon: mdi:fan
    entities:
      - group.ventilation
  sensors_view:
    name: Sensorer
    view: yes
    icon: mdi:thermometer
    entities:
      - group.thermometers
      - group.hygrometers
  automation_view:
    name: Automation
    view: yes
    icon: mdi:home-automation
    entities:
      - group.all_automations
  outdoor_lights:
    name: Utebelysning
    view: no
    entities:
      - switch.Baksida
      - switch.Entre
      - switch.Balkong
  window_lights:
    name: Fönsterbelysning
    view: no
    entities:
      - switch.van3_fonster1
      - switch.van3_fonster2
  radio_1:
    name: Radio vån 1
    view: no
    entities:
      - input_select.radio_1_kanal
      - input_number.radio_1_volume
  radio_2:
    name: Radio vån 3
    view: no
    entities:
      - input_select.radio_3_kanal
      - input_number.radio_3_volume
  thermometers:
    name: Temperatur
    view: no
    entities:
      - sensor.frys_temperature
      - sensor.hall_nere_temperature
      - sensor.hall_uppe_temperature
      - sensor.vardagsrum_temperature
      - sensor.ute_temperature
      - sensor.vning_3_temperature
      - sensor.vind_temperature
  hygrometers:
    name: Fuktighet
    view: no
    entities:
      - sensor.hall_nere_humidity
      - sensor.hall_uppe_humidity
      - sensor.ute_humidity
      - sensor.ute_temperature_2
  ventilation:
    name: Ventilation
    view: no
    entities:
      - sensor.fan_speed
      - input_number.fan_speed
      - sensor.temperature_set
      - input_number.temperature_set
      - sensor.filter_age
      - sensor.replace_in
      - sensor.supply_air
      - sensor.extract_air
      - sensor.exhaust_air
  doors:
    name: Dörrar
    view: no
    entities:
      - binary_sensor.entredorr
      - binary_sensor.altandorr
      - binary_sensor.balkongdorr

logger:
  default: info
  logs:
    urllib3.connectionpool: critical

http:
  api_password: !secret ha_api_password
  # Set to 1 to enable development mode
  # development: 1

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: home_telegram
    platform: telegram
    chat_id: !secret telegram_chat_id 

tellstick:
  signal_repetitions: 3

device_tracker:
  platform: asuswrt
  host: 192.168.1.1
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  track_new_devices: no
  protocol: telnet

modbus:
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 9600
  stopbits: 1
  bytesize: 8
  parity: N

sensor:
  - platform: tellstick
    only_named: 1
    11: Frys
    31: Ute
    80: Våning 3
    53: Vind
    datatype_mask: 1
  
  - platform: modbus
    registers:
      - name: Fan Speed
        slave: 1
        register: 100
        scale: 1
        offset: 0
      - name: Temperature set
        slave: 1
        register: 206
      - name: Supply air
        unit_of_measurement: °C
        slave: 1
        register: 213
        scale: 0.1
        precision: 1
      - name: Extract air
        unit_of_measurement: °C
        slave: 1
        register: 214
        scale: 0.1
        precision: 1
      - name: Exhaust air
        unit_of_measurement: °C
        slave: 1
        register: 215
        scale: 0.1
        precision: 1
      - name: Filter age
        unit_of_measurement: days
        slave: 1
        register: 601

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  thermometers: 1
  hygrometers: 1
  smartplugs: 1
  alarm: 1

frontend:

conversation:

history:

logbook:

sun:

media_player:
  - platform: cast
    host: 192.168.1.206
  - platform: cast
    host: 192.168.1.174

automation:
  - alias: radio_1 remote on
    trigger:
      - platform: state
        entity_id: switch.remotepower
    condition:
      condition: state
      entity_id: switch.remotepower
      state: 'on'
    action:
      entity_id: input_select.radio_1_kanal
      service: input_select.select_option
      data:
        option: "Radio Paradise"
  
  - alias: radio_1 remote off
    trigger:
      - platform: state
        entity_id: switch.remotepower
    condition:
      condition: state
      entity_id: switch.remotepower
      state: 'off'
    action:
      entity_id: input_select.radio_1_kanal
      service: input_select.select_option
      data:
        option: "Av"
  
  - alias: radio_1 remote swich station next
    trigger:
      - platform: state
        entity_id: switch.remotechannel
    condition:
      condition: state
      entity_id: switch.remotechannel
      state: 'off'
    action:
      entity_id: input_select.radio_1_kanal
      service: input_select.select_next
  
  - alias: radio_1 remote switch station previous
    trigger:
      - platform: state
        entity_id: switch.remotechannel
    condition:
      condition: state
      entity_id: switch.remotechannel
      state: 'on'
    action:
      entity_id: input_select.radio_1_kanal
      service: input_select.select_previous
  
  - alias: radio_1 remote volume up
    trigger:
      - platform: state
        entity_id: switch.remotevolume
    condition:
      condition: state
      entity_id: switch.remotevolume
      state: 'off'
    action:
      service: input_number.set_value
      entity_id: input_number.radio_1_volume
      data_template:
        value: '{{ float(states.input_number.radio_1_volume.state) + 10 }}'
  
  - alias: radio_1 remote volume down
    trigger:
      - platform: state
        entity_id: switch.remotevolume
    condition:
      condition: state
      entity_id: switch.remotevolume
      state: 'on'
    action:
      service: input_number.set_value
      entity_id: input_number.radio_1_volume
      data_template:
        value: '{{ float(states.input_number.radio_1_volume.state) - 10 }}'

  - alias: Change radio 1 volume
    trigger:
      - platform: state
        entity_id: input_number.radio_1_volume
    action:
      service: media_player.volume_set
      entity_id: media_player.radio_1
      data_template:
        volume_level: '{{ float(states.input_number.radio_1_volume.state) / 100 }}'
  
  - alias: Change radio 3 volume
    trigger:
      - platform: state
        entity_id: input_number.radio_3_volume
    action:
      service: media_player.volume_set
      entity_id: media_player.radio_3
      data_template:
        volume_level: '{{ float(states.input_number.radio_3_volume.state) / 100 }}'

#  - alias: Roof window open warning
#    trigger:
#      platform: time
#      minutes: 15
#      seconds: 0
#      after: '21:00:00'
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: switch.Takfonster1
#        state: 'on'
#      - condition: state
#        entity_id: switch.Takfonster2
#        state: 'on'
#    action:
#      service: notify.home_telegram
#      data:
#        message: Roof window open


  - alias: Turn on lights outside at sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.Ute

  - alias: Turn off lights outside at sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      service: homeassistant.turn_off
      entity_id: group.Ute

  - alias: Turn off radio
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
        to: 'armed_away'
      - platform: state
        entity_id: input_select.radio_1_kanal
        to: Av
    action:
      service: media_player.media_pause
      entity_id: media_player.radio_1

  - alias: Notify alarm state
    trigger:
      - platform: state 
        entity_id: alarm_control_panel.alarm_1
    action:
      service: notify.home_telegram
      data:
        title: alarm
      data_template:
        message: >
          {{ '*' ~ trigger.to_state.state ~ '*'|replace('_', ' ') }}
          by {{ trigger.to_state.attributes.changed_by }}
  
  - alias: Notify door bell
    trigger:
      - platform: state
        entity_id: switch.ringklocka
    condition:
      - condition: state
        entity_id: switch.ringklocka
        state: 'on'
    action:
      service: notify.home_telegram
      data:
        title: ringklocka
        message: ding dong
  
  - alias: Turn on window lights floor three at sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.fnster

  - alias: Turn off third floor window light in the evening
    trigger:
      platform: time
      at: '22:30:00'
    action:
      service: homeassistant.turn_off
      entity_id: group.fnster

  - alias: Start Radio 1
    trigger:
      platform: state
      entity_id: input_select.radio_1_kanal
    action:
      - entity_id: script.ON
        service: script.start_radio_1
  
  - alias: Start Radio 3
    trigger:
      platform: state
      entity_id: input_select.radio_3_kanal
    action:
      - entity_id: script.ON
        service: script.start_radio_3

  - alias: Set fan speed
    trigger:
      platform: state
      entity_id: input_number.fan_speed
    action:
      service: modbus.write_register
      data:
        unit: 1
        address: 100
      data_template:
        value: '{{ states.input_number.fan_speed.state|int }}'

  - alias: Set fan speed number value
    trigger:
      platform: state
      entity_id: sensor.fan_speed
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.fan_speed
        value: '{{ states.sensor.fan_speed.state }}'
  
  - alias: Set temperature set
    trigger:
      platform: state
      entity_id: input_number.temperature_set
    action:
      service: modbus.write_register
      data:
          unit: 1
          address: 206
      data_template:
          value: '{{ states.input_number.temperature_set.state|int }}'

  - alias: Set temperature set number value
    trigger:
      platform: state
      entity_id: sensor.temperature_set
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.temperature_set
        value: '{{ states.sensor.temperature_set.state }}'
  
input_select:
  radio_1_kanal:
    name: Kanal
    options:
      - Av
      - Radio Paradise
      - P1
      - P3
      - P4
      - Radioapan
      - P4 Bjällerklang
    initial: Av
  radio_3_kanal:
    name: Kanal
    options:
      - Av
      - Radio Paradise
      - P1
      - P3
      - P4
      - Radioapan
      - P4 Bjällerklang
    initial: Av

input_number:
  radio_1_volume:
    name: Volym
    min: 0
    max: 100
    initial: 35
    step: 1
    unit_of_measurement: '%'
  radio_3_volume:
    name: Volym
    min: 0
    max: 100
    initial: 35
    step: 1
    unit_of_measurement: '%'
  fan_speed:
    name: Fan speed
    min: 1
    max: 3
    step: 1
    unit_of_measurement: step
  temperature_set:
    name: Temperature set
    min: 1
    max: 3
    step: 1
    unit_of_measurement: step

script:
  start_radio_1:
    alias: Start Radio 1
    sequence:
      - alias: Power on
        service: media_player.turn_on   
        data:
          entity_id: media_player.radio_1     
      - alias: Set volume  
        service: media_player.volume_set
        data:      
          entity_id: media_player.radio_1
        data_template:
          volume_level: '{{ float(states.input_number.radio_1_volume.state) / 100 }}'
      - alias: Play
        service: media_player.play_media
        data_template:
          entity_id: media_player.radio_1
          media_content_type: video/mp4
          media_content_id: >
            {% if is_state('input_select.radio_1_kanal', 'Radio Paradise') %}
              http://stream-uk1.radioparadise.com/rp_192.ogg
            {% elif is_state('input_select.radio_1_kanal', 'P1') %}
              http://sverigesradio.se/topsy/direkt/132-hi-mp3
            {% elif is_state('input_select.radio_1_kanal', 'P3') %}
              http://sverigesradio.se/topsy/direkt/164-hi-mp3
            {% elif is_state('input_select.radio_1_kanal', 'P4') %}
              http://sverigesradio.se/topsy/direkt/212-hi-mp3
            {% elif is_state('input_select.radio_1_kanal', 'Radioapan') %}
              http://sverigesradio.se/topsy/direkt/2755-hi-mp3
            {% elif is_state('input_select.radio_1_kanal', 'P4 Bjällerklang') %}
              http://sverigesradio.se/topsy/direkt/3034-hi-mp3
            {% endif %}
  start_radio_3:
    alias: Start Radio 3
    sequence:
      - alias: Power on
        service: media_player.turn_on   
        data:
          entity_id: media_player.radio_3     
      - alias: Set volume  
        service: media_player.volume_set
        data:
          entity_id: media_player.radio_3
        data_template:
          volume_level: '{{ float(states.input_number.radio_3_volume.state) / 100 }}'
      - alias: Play
        service: media_player.play_media
        data_template:
          entity_id: media_player.radio_3
          media_content_type: video/mp4
          media_content_id: >
            {% if is_state('input_select.radio_3_kanal', 'Radio Paradise') %}
              http://stream-uk1.radioparadise.com/rp_192.ogg
            {% elif is_state('input_select.radio_3_kanal', 'P1') %}
              http://sverigesradio.se/topsy/direkt/132-hi-mp3
            {% elif is_state('input_select.radio_3_kanal', 'P3') %}
              http://sverigesradio.se/topsy/direkt/164-hi-mp3
            {% elif is_state('input_select.radio_3_kanal', 'P4') %}
              http://sverigesradio.se/topsy/direkt/212-hi-mp3
            {% elif is_state('input_select.radio_3_kanal', 'Radioapan') %}
              http://sverigesradio.se/topsy/direkt/2755-hi-mp3
            {% elif is_state('input_select.radio_3_kanal', 'P4 Bjällerklang') %}
              http://sverigesradio.se/topsy/direkt/3034-hi-mp3
            {% endif %}

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.1.57:8080/video
    username: !secret cam_username
    password: !secret cam_password
