homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 57.43
  longitude: 11.59
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  customize:
    sun.sun:
      hidden: true
    script.radio_paradise:
      hidden: true
    script.sr_p1:
      hidden: true
    script.sr_p3:
      hidden: true
    script.sr_p4:
      hidden: true
    script.sr_radioapan:
      hidden: true
    script.start_radio:
      hidden: true
    group.Switch:
      hidden: true
    media_player.kodi:
      hidden: true
    media_player.tak:
      hidden: true
    media_player.tvcast:
      hidden: true

http: !include http.yaml

tellstick:

device_tracker: !include devicetracker.yaml

# media_player:
#   - platform: kodi
#     url: http://192.168.1.15:8080/jsonrpc

#  - platform: samsungtv
#    host: 192.168.1.33

sensor:
  platform: tellstick
  only_named: 1
  11: Frys
  31: Ute
  80: Våning 3
  53: Vind
  datatype_mask: 1

verisure: !include verisure.yaml

discovery:

frontend:

conversation:

history:

logbook:

sun:

group:
  Belysning:
    view: yes
    entities:
      - group.Ute
      - group.Fnster
  Multimedia:
    view: yes
    entities:
      - group.Musik
  Klimat:
    view: yes
    entities:
      - group.Temperatur
      - group.Fuktighet
  Ute:
    - switch.Baksida
    - switch.Entre
    - switch.Balkong
  Fönster:
    - switch.van3_fonster1
    - switch.van3_fonster2
  Radio:
    - media_player.tak
    - input_select.kanal
    - input_slider.radio_volume
  Temperatur:
    - sensor.frys_temperature
    - sensor.hall_nere_temperature
    - sensor.hall_uppe_temperature
    - sensor.vardagsrum_temperature
    - sensor.ute_temperature
    - sensor.vning_3_temperature
    - sensor.vind_temperature
  Fuktighet:
    - sensor.hall_nere_humidity
    - sensor.hall_uppe_humidity
    - sensor.ute_humidity
    - sensor.ute_temperature_2

automation:
  - alias: Change radio volume
    trigger:
      - platform: state
        entity_id: input_slider.radio_volume
    action:
      service: media_player.volume_set
      entity_id: media_player.tak
      data_template:
        volume_level: '{{ float(states.input_slider.radio_volume.state) / 100 }}'

  - alias: LED laudery on
    trigger:
      platform: state
      entity_id: switch.move
      from: switch.off
      to: switch.on
    action:
      service: homeassistant.turn_on
      entity_id: switch.tvttstuga_led
  
  - alias: LED laudery off
    trigger:
      platform: state
      entity_id: switch.move
      from: switch.on
      to: switch.off
    action:
      service: homeassistant.turn_off
      entity_id: switch.tvttstuga_led

  - alias: Turn on lights outside at sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.Ute

  - alias: Turn off lights outside at sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      service: homeassistant.turn_off
      entity_id: group.Ute

  - alias: Turn off radio
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
        state: 'armed_away'
      - platform: state
        entity_id: input_select.kanal
        state: Av
    action:
      service: media_player.media_pause
      entity_id: media_player.tak
  
  - alias: Turn on window lights floor three at sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.fnster

  - alias: Turn off third floor window light in the evening
    trigger:
      platform: time
      after: '22:30:00'
    action:
      service: homeassistant.turn_off
      entity_id: group.fnster

  - alias: Start Radio
    trigger:
      platform: state
      entity_id: input_select.kanal
    action:
      entity_id: script.ON
      service: script.start_radio
  
input_select:
  kanal:
    name: Kanal
    options:
      - Av
      - Radio Paradise
      - P1
      - P3
      - P4
      - Radioapan
    initial: Av

input_slider:
  radio_volume:
    name: Volym
    min: 0
    max: 100
    initial: 35

script:
  start_radio:
    alias: Start Radio
    sequence:
      - alias: Power on    
        service: media_player.turn_on   
        data:
          entity_id: media_player.tak     
      - alias: Set volume  
        service: media_player.volume_set
        data:      
          entity_id: media_player.tak     
          volume_level: 0.35
      - alias: Play
        service: media_player.play_media
        data_template:
          entity_id: media_player.tak
          media_content_type: video/mp4
          media_content_id: >
            {% if is_state('input_select.kanal', 'Radio Paradise') %}
              http://stream-dc1.radioparadise.com/rp_192m.ogg
            {% elif is_state('input_select.kanal', 'P1') %}
              http://sverigesradio.se/topsy/direkt/132-hi-mp3
            {% elif is_state('input_select.kanal', 'P3') %}
              http://sverigesradio.se/topsy/direkt/164-hi-mp3
            {% elif is_state('input_select.kanal', 'P4') %}
              http://sverigesradio.se/topsy/direkt/212-hi-mp3
            {% elif is_state('input_select.kanal', 'Radioapan') %}
              http://sverigesradio.se/topsy/direkt/2755-hi-mp3
            {% endif %}
