homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 57.7066
  longitude: 11.9672
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

    #tts:
    #- platform: google_translate

# Show the introduction message on startup.
#introduction:

discovery:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
        # api_password: !secret ha_api_password
        #   trusted_networks:
        #     - 172.21.0.1
#  ssl_certificate: /cert/server.crt
#  ssl_key: /cert/server.key

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'sv'

modbus:
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 9600
  stopbits: 1
  bytesize: 8
  parity: N

rfxtrx:                                                                          
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A129KL64-if00-port0             
  debug: False

asuswrt:
  host: 192.168.1.1
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  protocol: telnet
  port: 23

sensor:
  - platform: yr
  - platform: modbus
    registers:
      - name: Fan Speed
        slave: 1
        register: 100
        scale: 1
        offset: 0
      - name: Temperature set
        slave: 1
        register: 206
      - name: Supply air
        unit_of_measurement: °C
        slave: 1
        register: 213
        scale: 0.1
        precision: 1
      - name: Extract air
        unit_of_measurement: °C
        slave: 1
        register: 214
        scale: 0.1
        precision: 1
      - name: Exhaust air
        unit_of_measurement: °C
        slave: 1
        register: 215
        scale: 0.1
        precision: 1
      - name: Filter age
        unit_of_measurement: days
        slave: 1
        register: 601

  - platform: rfxtrx                                                             
    automatic_add: True                                                          
    devices:                                                                     
      0a5201023501009d330060:                                                    
        name: Vind                                                               
        data_type:                                                               
          - Temperature                                                          
          - Humidity                                                             
      0a520106720200d81e0279:                                                    
        name: Våning 3                                                           
        data_type:                                                               
          - Temperature                                                          
          - Humidity                                                             
      0a5201047a0400c4410079:                                                    
        name: Ute                                                                
        data_type:                                                               
          - Temperature                                                          
          - Humidity

  - platform: template                                                           
    sensors:                                                                     
      thermometer_hygrometer_floor_3:                                            
        friendly_name: "Våning 3"                                                
        entity_id:                                                               
          - sensor.vaning_3_temperature                                          
          - sensor.vaning_3_humidity                                             
        value_template: "{{ states.sensor.vaning_3_temperature.state }}°C / {{ states.sensor.vaning_3_humidity.state }}%"
        icon_template: mdi:thermometer                                           
      thermometer_hygrometer_hallway_floor_1:                                    
        friendly_name: "Våning 1"                                                
        entity_id:                                                               
          - sensor.hall_nere_temperature                                         
          - sensor.hall_nere_humidity                                            
        value_template: "{{ states.sensor.hall_nere_temperature.state }}°C / {{ states.sensor.hall_nere_humidity.state }}%"
        icon_template: mdi:thermometer                                           
      thermometer_hygrometer_hallway_floor_2:                                    
        friendly_name: "Våning 2"                                                
        entity_id:                                                               
          - sensor.hall_uppe_temperature                                         
          - sensor.hall_uppe_humidity                                            
        value_template: "{{ states.sensor.hall_uppe_temperature.state }}°C / {{ states.sensor.hall_uppe_humidity.state }}%"
        icon_template: mdi:thermometer                                           
      thermometer_hygrometer_outdoor:                                            
        friendly_name: "Ute"                                                     
        entity_id:                                                               
          - sensor.ute_temperature                                               
          - sensor.ute_humidity                                                  
        value_template: "{{ states.sensor.ute_temperature.state }}°C / {{ states.sensor.ute_humidity.state }}%"
        icon_template: mdi:thermometer                                           
      thermometer_hygrometer_attic:                                              
        friendly_name: "Vind"                                                    
        entity_id:                                                               
          - sensor.vind_temperature                                              
          - sensor.vind_humidity                                                 
        value_template: "{{ states.sensor.vind_temperature.state }}°C / {{ states.sensor.vind_humidity.state }}%"
        icon_template: mdi:thermometer   

switch:                                                                          
  platform: rfxtrx
  automatic_add: false
  devices:                                                                       
    0b11000c000e8e5001000080:                                                    
      name: baksida                                                              
    0b110019000e8e5201000070:                                                    
      name: entre                                                                
    0b11002c000e8e5101000080:                                                    
      name: balkong                                                              
    0b110004000e8e5501000070:                                                    
       name: van3_fonster1                                                       
    0b110005000e8e5601000070:                                                    
       name: van3_fonster2                                                       
    0b110089000e8e4e01000080:                                                    
      name: tvattstuga                                                           
    0b11009600ceb54e02010f80:                                                    
      name: garderob                                                             
    0b1100a500ceb53a01010f70:                                                    
      name: pertelefon                                                           
    0b1100c0016fc80a0e010f80:                                                    
      name: radio1switch                                                         
    0b11008a0117f79e02010f80:                                                    
      name: ringklocka                                                           
    0b110006012c34740a000070:                                                    
      name: sovrumsfonster                                                       
    0b11001700ed623e04010f80: 
      name: wally
    0b11000701e067d20d010f70:
      name: secto
    0b11001a01e067d20f010f70:
      name: glob2
    0b11001e01e067d20e010f70:
      name: glob3
                                                                                 
light:                                                                           
  platform: rfxtrx                                                               
  devices:                                                                       
    0b11001700ed623e02010f80:                                                    
      name: cluster                                                              
    0b11001700ed623e03010f80:                                                    
      name: stella                                                               
    0b11001700ed623e12010f80:                                                    
      name: soffa    

cover:                                                                           
  - platform: rfxtrx                                                             
    signal_repetitions: 2                                                        
    devices:                                                                     
      071a03000a0b0c01:                                                          
        name: Terrass
      071a03000a0b0d01:                                                          
        name: Sovrum

verisure:                                                                        
  username: !secret verisure_username                                            
  password: !secret verisure_password                                            
  thermometers: 1                                                                
  hygrometers: 1                                                                 
  smartplugs: 1                                                                  
  alarm: 1

input_select:                                                                    
  radio_1_kanal:                                                                 
    name: Kanal                                                                  
    options:                                                                     
      - Av                                                                       
      - Radio Paradise                                                           
      - P1                                                                       
      - P3                                                                       
      - P4                                                                       
      - Radioapan                                                                
    initial: Av                                                                  
  vaning_3_kanal:                                                                 
    name: Kanal                                                                  
    options:                                                                     
      - Av                                                                       
      - Radio Paradise                                                           
      - P1                                                                       
      - P3                                                                       
      - P4                                                                       
      - Radioapan                                                                
    initial: Av

input_number:
  radio_1_volume:
    name: Volym
    min: 0
    max: 100
    initial: 35
    step: 1
    unit_of_measurement: '%'
  vaning_3_volume:
    name: Volym
    min: 0
    max: 100
    initial: 35
    step: 1
    unit_of_measurement: '%'
  fan_speed:
    name: Fan speed
    min: 1
    max: 3
    step: 1
    unit_of_measurement: step
  temperature_set:
    name: Temperature set
    min: 1
    max: 3
    step: 1
    unit_of_measurement: step

camera:                                                                          
  - platform: mjpeg                                                              
    mjpeg_url: http://192.168.1.57:8080/video                                    
    username: !secret cam_username                                               
    password: !secret cam_password

telegram_bot:                                                                    
  - platform: polling                                                            
    api_key: !secret telegram_api_key                                            
    allowed_chat_ids:                                                            
      - !secret telegram_chat_id

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.133
    token: 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
