homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 57.43
  longitude: 11.59
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  customize:
    sun.sun:
      hidden: true
    script.radio_paradise:
      hidden: true
    script.sr_p1:
      hidden: true
    script.sr_p3:
      hidden: true
    script.sr_p4:
      hidden: true
    script.sr_radioapan:
      hidden: true
    script.start_radio:
      hidden: true
    group.Switch:
      hidden: true
    media_player.kodi:
      hidden: true
    media_player.tak:
      hidden: true
    media_player.tvcast:
      hidden: true
    media_player.kdl55w808c:
      hidden: true

http: !include http.yaml

notify: !include telegram.yaml

tellstick:
  signal_repetitions: 3

device_tracker: !include devicetracker.yaml

modbus:
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 9600
  stopbits: 1
  bytesize: 8
  parity: N

sensor:
  - platform: tellstick
    only_named: 1
    11: Frys
    31: Ute
    80: Våning 3
    53: Vind
    datatype_mask: 1
  
  - platform: modbus
    slave: 1
    registers:
      100:
        name: Fan speed
        unit:
      213:
        name: Supply air
        unit: °C
        scale: 0.1
      214:
        name: Extract air
        unit: °C
        scale: 0.1
      215:
        name: Exhaust air
        unit: °C
        scale: 0.1
      601:
        name: Filter age
        unit: days
      602:
        name: Replace in
        unit: months

verisure: !include verisure.yaml

discovery:

frontend:

conversation:

history:

logbook:

sun:

group:
  Belysning:
    view: yes
    entities:
      - group.Ute
      - group.Fnster
  Multimedia:
    view: yes
    entities:
      - group.Musik
  Klimat:
    view: yes
    entities:
      - group.Temperatur
      - group.Fuktighet
  Ute:
    - switch.Baksida
    - switch.Entre
    - switch.Balkong
  Fönster:
    - switch.van3_fonster1
    - switch.van3_fonster2
  Radio:
    - media_player.tak
    - input_select.kanal
    - input_slider.radio_volume
  Temperatur:
    - sensor.frys_temperature
    - sensor.hall_nere_temperature
    - sensor.hall_uppe_temperature
    - sensor.vardagsrum_temperature
    - sensor.ute_temperature
    - sensor.vning_3_temperature
    - sensor.vind_temperature
  Fuktighet:
    - sensor.hall_nere_humidity
    - sensor.hall_uppe_humidity
    - sensor.ute_humidity
    - sensor.ute_temperature_2
  Ventilation:
    - sensor.fan_speed
    - input_slider.fan_speed
    - sensor.filter_age
    - sensor.replace_in
    - sensor.supply_air
    - sensor.extract_air
    - sensor.exhaust_air

automation:
  - alias: Change radio volume
    trigger:
      - platform: state
        entity_id: input_slider.radio_volume
    action:
      service: media_player.volume_set
      entity_id: media_player.tak
      data_template:
        volume_level: '{{ float(states.input_slider.radio_volume.state) / 100 }}'

#  - alias: Roof window open warning
#    trigger:
#      platform: time
#      minutes: 15
#      seconds: 0
#      after: '21:00:00'
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: switch.Takfonster1
#        state: 'on'
#      - condition: state
#        entity_id: switch.Takfonster2
#        state: 'on'
#    action:
#      service: notify.notify
#      data:
#        message: Roof window open


  - alias: Turn on lights outside at sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.Ute

  - alias: Turn off lights outside at sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      service: homeassistant.turn_off
      entity_id: group.Ute

  - alias: Turn off radio
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
        state: 'armed_away'
      - platform: state
        entity_id: input_select.kanal
        state: Av
    action:
      service: media_player.media_pause
      entity_id: media_player.tak

  - alias: Notify alarm state
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
    action:
      service: notify.notify
      data_template:
        message: >
          alarm {{ trigger.to_state.state }}
          by {{ trigger.to_state.attributes.changed_by }}
  
  - alias: Turn on window lights floor three at sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.fnster

  - alias: Turn off third floor window light in the evening
    trigger:
      platform: time
      after: '22:30:00'
    action:
      service: homeassistant.turn_off
      entity_id: group.fnster

  - alias: Start Radio
    trigger:
      platform: state
      entity_id: input_select.kanal
    action:
      - entity_id: script.ON
        service: script.start_radio

  - alias: Set fan speed
    trigger:
      platform: state
      entity_id: input_slider.fan_speed
    action:
      service: modbus.write_register
      data_template:
        unit: 1
        address: 100
        value: '{{ states.input_slider.fan_speed.state }}'
  
input_select:
  kanal:
    name: Kanal
    options:
      - Av
      - Radio Paradise
      - P1
      - P3
      - P4
      - Radioapan
    initial: Av

input_slider:
  radio_volume:
    name: Volym
    min: 0
    max: 100
    initial: 35
    step: 1
  fan_speed:
    name: Fan speed
    min: 0
    max: 4
    initial: 2
    step: 1

script:
  start_radio:
    alias: Start Radio
    sequence:
      - alias: Power on    
        service: media_player.turn_on   
        data:
          entity_id: media_player.tak     
      - alias: Set volume  
        service: media_player.volume_set
        data:      
          entity_id: media_player.tak
        data_template:
          volume_level: '{{ float(states.input_slider.radio_volume.state) / 100 }}'
      - alias: Play
        service: media_player.play_media
        data_template:
          entity_id: media_player.tak
          media_content_type: video/mp4
          media_content_id: >
            {% if is_state('input_select.kanal', 'Radio Paradise') %}
              http://stream-dc1.radioparadise.com/rp_192m.ogg
            {% elif is_state('input_select.kanal', 'P1') %}
              http://sverigesradio.se/topsy/direkt/132-hi-mp3
            {% elif is_state('input_select.kanal', 'P3') %}
              http://sverigesradio.se/topsy/direkt/164-hi-mp3
            {% elif is_state('input_select.kanal', 'P4') %}
              http://sverigesradio.se/topsy/direkt/212-hi-mp3
            {% elif is_state('input_select.kanal', 'Radioapan') %}
              http://sverigesradio.se/topsy/direkt/2755-hi-mp3
            {% endif %}
